In [2]:
import numpy as np
print("done")

done


In [4]:
l1=[1,24,5,6]
l2=[2,3,45,56]
sumList=[]
#shorter way 
len1=len(l1)
len2=len(l2)
minLen=min(len1,len2)
for i in range(0,minLen):
    sumList.append(l1[i]+l2[i])
print("sum list is :", sumList , sep="\n")

sum list is :
[3, 27, 50, 62]


In [6]:
sumList=l1+l2
print("sum list is :", sumList , sep="\n")

sum list is :
[1, 24, 5, 6, 2, 3, 45, 56]


In [8]:
"""
it just append the 2 list 
 but pehle wale mai 2 list kai elements ka sum kra rhe hai hm
now,
"""
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
sum=arr1+arr2
print("sum list is :", sum , sep="\n")

sum list is :
[ 7  9 11 13 15]


In [10]:
# condition to check
arr_bool = arr1>=3
print('check for condition:' , arr_bool , end='\n\n')
print('what ste the values that satisfying the condtion ', arr1[arr_bool])

check for condition: [False False  True  True  True]

what ste the values that satisfying the condtion  [3 4 5]


In [12]:
#simplify version
arr3=arr1[arr1>=2]
print(arr3)

[2 3 4 5]


In [14]:
arr3=arr1[arr2>=2]
print(arr3)

[1 2 3 4 5]


In [16]:
# this method used as slicing , operations on higher levels:
a1=np.array([[1,2,3],[4,5,6]])
a2=np.array([[11,12,13],[14,15,16]])
print("1st array :", a1 , sep="\n",end='\n\n')
print("2nd array :", a1 , sep="\n",end='\n\n')
print("final array :", a2-a1 , sep="\n",end='\n\n')


1st array :
[[1 2 3]
 [4 5 6]]

2nd array :
[[1 2 3]
 [4 5 6]]

final array :
[[10 10 10]
 [10 10 10]]



In [24]:
# functions
arangeArr=np.array(list(range(1,15,2)))
print('using complex nested functions' , arangeArr , end='\n\n')

# 1 arange method:-
arange_arr=np.arange(1,15,2)
print('using simple numpy functions: ',arange_arr)

# 2 an array with zero:-
z = np.zeros(5)
print('1D array' , z , sep="\n" , end='\n\n')

zeroArr2D = np.zeros( [5,3] ,dtype=float)
print('1D array', zeroArr2D , sep="\n" , end='\n\n')

# array with one's
ones = np.ones(5)
print('1D array' , ones , sep="\n" , end='\n\n')

ones2D = np.ones( [5,3] , dtype=int)
print('1D array', ones2D , sep="\n" , end='\n\n')


# for numbers other than 0,1
print(np.full(shape=5,fill_value=5) , end="\n\n" )
print(np.full(shape=(5,5) , fill_value=3) , end='\n\n')


using complex nested functions [ 1  3  5  7  9 11 13]

using simple numpy functions:  [ 1  3  5  7  9 11 13]
1D array
[0. 0. 0. 0. 0.]

1D array
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

1D array
[1. 1. 1. 1. 1.]

1D array
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

[5 5 5 5 5]

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]



In [26]:
# random value 
# this random value is usually b/w 0 and 1 ; 
np.random.random((3,3))

array([[0.28666789, 0.4747312 , 0.51125968],
       [0.06121839, 0.09851621, 0.18689325],
       [0.22442672, 0.3337883 , 0.20772835]])

In [28]:
# random.randint and seed significance
np.random.seed(2)
print(np.random.randint(low=1,high=30,size=10))
np.random.randint(low=1,high=15,size=(3,3))

[ 9 16 14  9 23 12 19 12  9  8]


array([[ 3,  2, 12],
       [ 6, 11,  5],
       [13,  5,  6]])

In [32]:
import time
l1 = [i for i in range (200000)]
l2= [j**2 for j in range(200000)]
# starting clock
start=time.time()
multi=list(map(lambda x, y:x*y , l1,l2))
end=time.time()
print("total time consumed: ",end-start)

total time consumed:  0.035600900650024414


In [34]:
a1=np.array([i for i in range(200000)])
a2=np.array([j**2 for j in range(200000)])
# starting clock
start=time.time()
multiplication=a1*a2
end=time.time()
print("total time consumed: ",end-start)

total time consumed:  0.0010118484497070312
