In [2]:
#import
import numpy as np
print("package successfully imported")

package successfully imported


In [8]:
record = [1,2,3,4,5,6]
print(type(record))
print(record)

<class 'list'>
[1, 2, 3, 4, 5, 6]


In [10]:
recordArr=np.array(record)
print(type(recordArr))
print(recordArr)

<class 'numpy.ndarray'>
[1 2 3 4 5 6]


In [12]:
t = (1,2,3,4,5,6)
print(type(t))
print(t)
tArr=np.array(t)
print(type(tArr))
print(tArr)

<class 'tuple'>
(1, 2, 3, 4, 5, 6)
<class 'numpy.ndarray'>
[1 2 3 4 5 6]


In [16]:
arr2d =  np.array([[1,2,3],[4,5,6]])
print("2D-array :\n",arr2d)

2D-array :
 [[1 2 3]
 [4 5 6]]
